language: java
sudo: false
jdk:
  - openjdk11
addons:
    apt:
        packages:
            - maven
  
cache:
    directories:
        - $HOME/.m2

after_success:
    - bash <(curl -s https://codecov.io/bash)
    
