import it.cnr.isti.labsedc.glimpse.event.GlimpseBaseEventAbstract; 
import it.cnr.isti.labsedc.glimpse.event.GlimpseBaseEventSB;
import it.cnr.isti.labsedc.glimpse.event.GlimpseBaseEventFaceRecognition;
import it.cnr.isti.labsedc.glimpse.utils.UpdateRoom;

declare GlimpseBaseEventAbstract
    @role( event )
    @timestamp( timeStamp )
end 


rule "UpdateParameter on internal DB" 

no-loop true 
salience 1 
dialect "java" 

when 
 	$bEvent:GlimpseBaseEventSB(
		this.isConsumed == false,
		this.isException == false); 
then			
	UpdateRoom.SetValue($bEvent);
	retract($bEvent);
end 

